name: rnaseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.12
  - pandas>=2.2.3
  - numpy>=1.24,<2.2
  - scipy>=1.15.1
  - matplotlib>=3.10.0
  - seaborn>=0.13.2
  - scikit-learn>=1.6.1
  - fastqc=0.12.1
  - cutadapt>=4.7
  - subread=2.0.8
  - samtools=1.21
  - hisat2=2.2.1
  - kallisto=0.51.1
  - multiqc
  - pip
  - pip:
    - docopt
    - xlrd==1.2.0 