# input data for preprocessing
input:
  # Preprocessing inputs in form of raw fastq files
  fastq_dir: "/Users/mukulsherekar/pythonProject/DEGCNN/fastq_files/PRJNA413568"
  fastq_pattern: "*.fastq.gz"
  paired_end: true

# output data for preprocessing
output:
  
  qc_dir: "/Users/mukulsherekar/pythonProject/DEGCNN/qc_files/PRJNA413568"
  qc_trimmed_dir: "/Users/mukulsherekar/pythonProject/DEGCNN/qc_files/PRJNA413568_Trim"
  trimmed_fastq_dir: "/Users/mukulsherekar/pythonProject/DEGCNN/fastq_trim/PRJNA413568"
  aligned_dir: "/Users/mukulsherekar/pythonProject/DEGCNN/hisat_files/PRJNA413568"
  counts_dir: "/Users/mukulsherekar/pythonProject/DEGCNN/counts"
  results_dir: "/Users/mukulsherekar/pythonProject/DEGCNN/results"
  # final_report: "tests/data/results/{sample}_final_report.md"

# Reference genome information
genome:
  # GTF annotation file
  gtf_file: "genome/gencode.v38.annotation.gtf"
  # Reference genome FASTA
  genome_fasta: "genome/GRCh38.p13.genome.fa"
  # Transcriptome FASTA
  transcriptome_fasta: "genome/gencode.v47.transcripts.fa.gz"

# Aligner configurations
aligners:
  hisat2:
    index_prefix: "genome/genome"
  kallisto:
    index: "genome/kallisto_index"
    fragment_length: 200
    fragment_sd: 20
    bootstrap: 100
  
    
parameters:
  step: "all"
  threads: 4
  memory: "8G"
  aligner: "kallisto"  # Default aligner to use

  # Quality control parameters
  min_quality: 20
  min_length: 36
  # Strandedness: "yes", "no", or "reverse"
  stranded: "reverse"
  quality_threshold: 20
  adapter_stringency: 0.9

pipeline_steps:
  - qc
  - alignment
  - quantification
  - multiqc  # For final QC report