# Combined configuration for preprocessing and postprocessing

# Input data for preprocessing
input:
  # Preprocessing inputs
  fastq_dir: "tests/data/raw_fastq"
  fastq_pattern: "*.fq.gz"
  paired_end: false
  
  # Postprocessing inputs
  # Use a wildcard if your pipeline supports it, or remove if these will be computed per sample
  counts_file: "tests/data/results/counts/{sample}_counts.tsv"
  kallisto_abundance: "tests/data/results/kallisto/{sample}_abundance.tsv"

# Output directories
output:
  # Base output directory
  results_dir: "tests/data/results/preprocessing"
  final_report: "tests/data/results/{sample}_final_report.md"
  
  
  # Preprocessing outputs
  qc_dir: "tests/data/results/preprocessing/qc"
  alignment_dir: "tests/data/results/preprocessing/aligned_reads"
  counts_dir: "tests/data/results/preprocessing/counts"
  
  # Postprocessing outputs
  postprocessing_dir: "tests/data/results/postprocessing"

# Reference genome information
genome:
  gtf_file: "/genome/gencode.v38.annotation.gtf"
  genome_fasta: "/genome/GRCh38.p13.genome.fa"
  transcriptome_fasta: "/genome/gencode.v47.transcripts.fa.gz"

# Aligner configurations
aligners:
  hisat2:
    index_prefix: "/genome/genome"
  kallisto:
    index: "/genome/kallisto_index"
    fragment_length: 200
    fragment_sd: 20

# Analysis parameters
parameters:
  quality_threshold: 20
  min_length: 36
  adapter_stringency: 0.9
  
  distribution: true
  top_genes: 15
  gene_threshold: 10
  expected_library_size: 0
  go_enrichment: true
  network_analysis: true
  top_percent: 5
  threads: 8

# Visualization settings (for postprocessing)
visualization:
  pca:
    color_by: "condition"
  volcano:
    log2fc_cutoff: 1.0
    padj_cutoff: 0.05
