# Snakemake configuration file

# Input data configuration
input:
  fastq_dir: "tests/data/raw_fastq"
  fastq_pattern: "*.fq.gz"
  paired_end: false
  counts_file: "tests/data/results/preprocessing/counts_hisat2/${sample}.bam_counts.tsv"
  kallisto_abundance: "tests/data/results/preprocessing/${sample}_kallisto/abundance.tsv"
  kallisto_h5: "tests/data/results/preprocessing/${sample}_kallisto/abundance.h5"

# Output directories
# Output directories
output:
  # Base output directories
  pre_results_dir: "tests/data/results/preprocessing"
  post_results_dir: "tests/data/results/postprocessing"
  
  # Preprocessing specific outputs
  qc_dir: "tests/data/results/preprocessing/qc"
  aligned_dir: "tests/data/results/preprocessing/aligned_reads"
  counts_dir: "tests/data/results/preprocessing/counts"
  
  # Postprocessing specific outputs (using wildcards if needed)
  sample_dir: "tests/data/results/postprocessing/{sample}"
  eda_dir: "tests/data/results/postprocessing/{sample}/exploratory"
  differential_dir: "tests/data/results/postprocessing/{sample}/differential"
  enrichment_dir: "tests/data/results/postprocessing/{sample}/enrichment"
  reports_dir: "tests/data/results/postprocessing/{sample}/reports"
  
  # Legacy directories (for backward compatibility)
  raw_data: "tests/data/raw_fastq"
  results: "tests/data/snakemake_results"
  logs: "logs"

# Reference genome information
genome:
  fasta: "genome/GRCh38.p13.genome.fa"
  gtf: "genome/gencode.v38.annotation.gtf"
  transcriptome: "genome/gencode.v47.transcripts.fa.gz"

# Aligner configurations
aligners:
  hisat2:
    index_prefix: "genome/genome"
    threads: 8
  kallisto:
    index: "genome/kallisto_index"
    threads: 8
    fragment_length: 200
    fragment_sd: 20
    bootstrap: 100
  salmon:
    index: "genome/salmon_index"
    library_type: "A"
    threads: 8

# Feature counting parameters
featurecounts:
  threads: 8
  strand: 0  # 0=unstranded, 1=stranded, 2=reversely stranded

# Quality control parameters
fastqc:
  threads: 8
  min_quality: 20
  min_length: 36

# Enabled analyses
enabled_analyses:
  # Preprocessing
  qc: true
  alignment: true
  quantification: true
  multiqc: true
  
  # Postprocessing
  eda: true
  qa: true
  kallisto: true
  enrichment: true
  report: true

# Analysis parameters
analysis:
  top_genes: 25  # Number of top genes to show in final report
  enrichment:
    gene_sets: ["GO_Biological_Process_2021", "GO_Molecular_Function_2021"]
    p_value_cutoff: 0.05
    go_analysis: true
    kegg_analysis: false
    top_percent: 5
  clustering:
    min_counts: 10  # Minimum counts to include in clustering
  differential:
    method: "DESeq2"  # Options: DESeq2, edgeR
    log2fc_cutoff: 1.0
    padj_cutoff: 0.05

# Parameters for general pipeline operation
parameters:
  step: "all"
  threads: 8
  memory: "8G"
  aligner: "kallisto"  # Default aligner to use
  fail_fast: false     # Whether to stop pipeline on first analysis failure
  stranded: "reverse"  # Strandedness: "yes", "no", or "reverse"
  adapter_stringency: 0.9

# Visualization parameters
visualization:
  theme: "default"  # Options: default, colorblind, publication
  pca:
    color_by: "condition"
    components: [1, 2]
  heatmap:
    cluster_rows: true
    cluster_cols: true
    show_rownames: false
  volcano:
    log2fc_cutoff: 1.0
    padj_cutoff: 0.05
    highlight_genes: []

# Pipeline steps
pipeline_steps:
  # Preprocessing steps
  - qc
  - alignment
  - quantification
  - multiqc
  
  # Postprocessing steps
  - eda
  - differential_expression
  - enrichment
  - report_generation

# Report configuration
reports:
  format: "markdown"  # Options: markdown, html, pdf
  include_code: false
  include_session_info: true
  final_report: "tests/data/results/{sample}_final_report.html"


