# Snakemake configuration file

# Directory structure
directories:
  raw_data: "tests/data/raw_fastq"
  results: "tests/data/snakemake_results"
  logs: "logs"

# Reference files
genome:
  fasta: "genome/GRCh38.p13.genome.fa"
  gtf: "genome/gencode.v38.annotation.gtf"
  transcriptome: "genome/gencode.v47.transcripts.fa.gz"

# Aligner configurations
aligners:
  hisat2:
    index_prefix: "genome/genome"
    threads: 8
  kallisto:
    index: "genome/kallisto_index"
    threads: 8
    fragment_length: 200  # For single-end reads
    fragment_sd: 20       # For single-end reads

# Feature counting parameters
featurecounts:
  threads: 8
  strand: 0  # 0=unstranded, 1=stranded, 2=reversely stranded

# Quality control parameters
fastqc:
  threads: 8

# Analysis parameters
analysis:
  top_genes: 25  # Number of top genes to show in final report
  enrichment:
    gene_sets: ["GO_Biological_Process_2021", "GO_Molecular_Function_2021"]
    p_value_cutoff: 0.05
  clustering:
    min_counts: 10  # Minimum counts to include in clustering
